on:
  push:
    branches:
      - main
jobs:
  check-out-code:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        # ESlint
      - name: "Lint Lightning Web Components"
        run: npm run lint:lwc
